### ISSUE TITLE
Create knitting pattern from valentina SVG

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/knittingpattern#59]
[Valentina Project](http://valentina-project.org/) allows us to create custom-fit measurements for knit clothes.
- [ ] Use an export option like the SVG export of valentina, to generate a file that can be rasterized to knit meshes using the gauge (measurement of how big a instruction is)
- [ ] create an issue that the kniteditor should load this
- [ ] create a tutorial video on how to export this file
  - [ ] create a video where the kniteditor loads the file

**Comment by jainaman224** [comment]
#58 Duplicate issue.
